version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    reviewers:
      - 'asHOH'
    commit-message:
      prefix: 'chore(deps)'
    groups:
      testing:
        patterns:
          - '@testing-library/*'
          - 'jest*'
        update-types:
          - 'minor'
          - 'patch'
      types:
        patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'
