version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Shanghai'
    target-branch: 'develop'
    open-pull-requests-limit: 3
    reviewers:
      - 'asHOH'
    commit-message:
      prefix: 'chore(deps)'
    groups:
      # Group all development dependencies together
      dev-dependencies:
        patterns:
          - '@testing-library/*'
          - '@types/*'
          - 'jest*'
          - 'eslint*'
          - 'prettier*'
          - 'husky*'
          - 'typescript*'
          - 'tailwindcss*'
          - 'postcss*'
          - 'autoprefixer*'
        update-types:
          - 'minor'
          - 'patch'
      # Group Next.js related dependencies
      nextjs-ecosystem:
        patterns:
          - 'next*'
          - 'react*'
          - '@next/*'
        update-types:
          - 'minor'
          - 'patch'
      # Group all other production dependencies
      production-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@testing-library/*'
          - '@types/*'
          - 'jest*'
          - 'eslint*'
          - 'prettier*'
          - 'husky*'
          - 'typescript*'
          - 'tailwindcss*'
          - 'postcss*'
          - 'autoprefixer*'
          - 'next*'
          - 'react*'
          - '@next/*'
        update-types:
          - 'minor'
          - 'patch'
