# DEPRECATED: GitHub Pages deployment
# This workflow has been replaced by Vercel deployment
# File kept for reference, will be removed after successful Vercel migration

name: Deploy to GitHub Pages (DEPRECATED)

on:
  # Disabled - use Vercel instead
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build for Production
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Try to download CI build artifacts
        if: github.event_name == 'workflow_run'
        id: download-ci-build
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: build-output-${{ github.sha }}
          path: out/
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Next.js cache from CI
        if: github.event_name == 'workflow_run' && steps.download-ci-build.outcome == 'success'
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: nextjs-cache-${{ github.sha }}
          path: .next/cache/
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean and build (if no CI artifacts)
        if: steps.download-ci-build.outcome != 'success'
        run: |
          rm -rf .next out
          if [ -f "next.config.js" ]; then
            rm next.config.js
          fi
          export NEXT_PUBLIC_BUILD_TIME=$(TZ='Asia/Shanghai' date '+%m月%d日 %H:%M')
          node update-sw-version.js
          echo "Service worker cache version updated successfully"
          npm run build

      - name: Verify build output
        run: |
          if [ ! -d "./out" ]; then
            echo "❌ Build failed - no output directory found"
            exit 1
          fi
          echo "✅ Build successful - $(du -sh ./out | cut -f1) generated"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    name: Deploy to Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Deployment summary
        run: |
          echo "## 🚀 Deployment Complete" >> $GITHUB_STEP_SUMMARY
          echo "✅ Site successfully deployed to: ${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
          echo "📅 Deployed at: $(date '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" == "workflow_run" ]; then
            echo "🔄 Triggered by successful CI workflow" >> $GITHUB_STEP_SUMMARY
          fi
